# Generated by Django 4.2.16 on 2024-09-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('comission_fixe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField()),
                ('statut_paiement', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_etudiants', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.niveau')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantsGroupes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_comission', models.DateField()),
                ('statut_comission', models.CharField(max_length=50)),
                ('Professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.professeur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.etudiant')),
            ],
        ),
    ]
