# Generated by Django 4.2.16 on 2024-09-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0002_etudiant_filiere_matiere_niveau_professeur_paiement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
