# Generated by Django 4.2.16 on 2024-09-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0003_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EtudiantsGroupes',
            new_name='EtudiantGroupe',
        ),
        migrations.RenameField(
            model_name='comission',
            old_name='Professeur',
            new_name='professeur',
        ),
        migrations.AlterField(
            model_name='comission',
            name='statut_comission',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='etudiantgroupe',
            unique_together={('etudiant', 'groupe')},
        ),
        migrations.AddIndex(
            model_name='comission',
            index=models.Index(fields=['professeur'], name='school_api__profess_96234b_idx'),
        ),
        migrations.AddIndex(
            model_name='comission',
            index=models.Index(fields=['etudiant'], name='school_api__etudian_46357e_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['etudiant'], name='school_api__etudian_c1ed9c_idx'),
        ),
    ]
