# Generated by Django 4.2.16 on 2024-10-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0004_rename_etudiantsgroupes_etudiantgroupe_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comission',
            name='school_api__profess_96234b_idx',
        ),
        migrations.RemoveIndex(
            model_name='comission',
            name='school_api__etudian_46357e_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='school_api__etudian_c1ed9c_idx',
        ),
        migrations.AddField(
            model_name='paiement',
            name='commission_percentage',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='paiement',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_api.groupe'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='statut_comission',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(max_length=50),
        ),
    ]
