# Generated by Django 4.2.16 on 2024-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0005_remove_comission_school_api__profess_96234b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='contact_urgence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(blank=True, default='Marocain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='nom_groupe',
            field=models.CharField(default='Groupe 1', max_length=100),
        ),
        migrations.AddField(
            model_name='professeur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='nationalite',
            field=models.CharField(blank=True, default='Marocain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(),
        ),
    ]
