# Generated by Django 4.2.16 on 2024-10-23 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0009_filiere_created_at_filiere_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='comission_fixe',
        ),
        migrations.AddField(
            model_name='groupe',
            name='commission_fixe',
            field=models.FloatField(default=120.0),
        ),
        migrations.AlterField(
            model_name='comission',
            name='date_comission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
