# Generated by Django 4.2.16 on 2024-11-05 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0011_etudiant_created_at_groupe_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='commission_fixe',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='professeur',
        ),
        migrations.CreateModel(
            name='GroupeProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_fixe', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.groupe')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.professeur')),
            ],
            options={
                'unique_together': {('groupe', 'professeur')},
            },
        ),
        migrations.CreateModel(
            name='GroupeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_api.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='groupe',
            name='matieres',
            field=models.ManyToManyField(through='school_api.GroupeMatiere', to='school_api.matiere'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='professeurs',
            field=models.ManyToManyField(through='school_api.GroupeProfesseur', to='school_api.professeur'),
        ),
    ]
