# Generated by Django 4.2.17 on 2024-12-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0014_remove_paiement_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='is_registration_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(max_length=100),
        ),
    ]
