# Generated by Django 4.2.17 on 2024-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0015_paiement_is_registration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='etablissement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
