# Generated by Django 4.2.17 on 2025-01-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0002_add_payment_month_fields'),
        ('school_api', '0016_etudiant_etablissement'),
    ]

    operations = [
    ]
